version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh # note: 사용하지 않으면 주석처리
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=local.password
      - MONGO_INITDB_DATABASE=local.db

  gateway:
    container_name: gateway
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo

  auth:
    container_name: auth
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    depends_on:
      - mongo
    env_file:
      - ./auth-server/.env

  event:
    container_name: event
    build:
      context: ./event-server
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - PORT=3002
    depends_on:
      - mongo
    env_file:
      - ./event-server/.env

volumes:
  mongo_data:
